### ISSUE TITLE
registry-auth-token doesn't match npm "nerf darting" behavior

### ISSUE THREAD

**Issue by zarenner** [rexxars/registry-auth-token#10]
npm “[nerf darts](https://github.com/npm/npm/blob/latest/lib/config/nerf-dart.js)” the registry URL to compute the settings prefix, effectively dropping everything after the last slash in the URL.

As such, a registry "https://contoso.pkgs.visualstudio.com/_packaging/MyFeed/npm/registry" (no trailing slash) would use the setting prefix "//contoso.pkgs.visualstudio.com/_packaging/MyFeed/npm/"

registry-auth-token however requires an exact match, so users would also have to also add auth settings for "//contoso.pkgs.visualstudio.com/_packaging/MyFeed/npm/registry" (unused by npm).

A possible workaround is to always use a trailing slash on the registry URL, in which case the nerf'ed URL will match the input, and both npm and registry-auth-token are happy.

registry-auth-token should use the same "nerf-darting" behavior as npm to be compatible.

**Comment by simonua** [comment]
To provide additional detail, here's the related post on Microsoft's Developer Community:

[https://developercommunity.visualstudio.com/content/problem/39633/update-notifier-not-working-after-switching-to-vst.html](https://developercommunity.visualstudio.com/content/problem/39633/update-notifier-not-working-after-switching-to-vst.html)

**Comment by rexxars** [comment]
Fixed in 3.1.1.
