### ISSUE TITLE
Using npm's programmatic API to get npm configs

### ISSUE THREAD

**Issue by zkochan** [rexxars/registry-auth-token#14]
Currently `registry-auth-token` uses `rc` to get the configs. However, npm does not use `rc`. npm has a very complex algorithm of getting its configs. Luckily, npm exposes a programmatic API to getting its configs.

pnpm needs to read these configs the same way npm does, so we're going to switch from `rc` to `npm`'s programmatic API.

How to make this change work with `registry-auth-token`? I think maybe we can pass an optional parameter `opts.npmrc` from outside and if it is passed in, `registry-auth-token` will use it instead of trying to get the configs using `rc`

* * * 

Ref https://github.com/pnpm/pnpm/issues/696

**Comment by rexxars** [comment]
What would be the value of `npmrc` be? Are you thinking something like this?

```js
const npm = require('npm')
const getAuthToken = require('registry-auth-token')
npm.load()
getAuthToken('some url', {npmrc: npm.config})
```

**Comment by zkochan** [comment]
Hm, probably it should be some function. To get values from npm, we have to run `npm.config.get('<key>')`.

So maybe 

```js
const npm = require('npm')
const getAuthToken = require('registry-auth-token')
npm.load()
getAuthToken('some url', {getConfig: key => npm.config.get(key)})
```

**Comment by zkochan** [comment]
I see there is also `npm.config.list` with an array of config objects. In priority order. I think we can just merge those configs in the correct order and in that case we can pass in an object of configs.

That would mean minimal changes in `registry-auth-token`

```js
const npm = require('npm')
const getAuthToken = require('registry-auth-token')
npm.load()
const config = Object.assign.apply(Object, npm.config.list.reverse())
getAuthToken('some url', {config})
```

**Comment by rexxars** [comment]
That last one seems like a good idea.
