### ISSUE TITLE
Parsing raw .npmrc contents

### ISSUE THREAD

**Issue by rarkins** [rexxars/registry-auth-token#18]
Hi, thank you for this library. I am using it as part of the [renovate](https://github.com/singapore/renovate) npm dependency checker.

I have a requirement to extract npm credentials from the contents of an `.npmrc` file for accessing private npm modules. i.e. I have the contents of the `.npmrc` assigned to a const in *memory* and not in the filesystem.

For example, my code needs to perform an npm registry lookup for private module `@hello/world`, and it has the raw contents of an applicable `.npmrc` file. Can this be done with the current library, or can you think of any workaround?

**Comment by zkochan** [comment]
Hi, you can just pass in the value of your const to registry-auth-token, via the `npmrc` option. 

There is a usage example about it in the readme:

```js
// Use the npm config that is passed in
console.log(getRegistryUrl('http://registry.foobar.eu/', {
  npmrc: {
    'registry': 'http://registry.foobar.eu/',
    '//registry.foobar.eu/:_authToken': 'qar'
  }
}))
```

**Comment by rarkins** [comment]
Thanks, @zkochan. I had seen that but was hesitant to start parsing the `.npmrc` file myself as there may be unknowns there.

To use my own file - and I have never looked into this file format before - I see something like:

```
ca=
cache=/Users/rhys/.npm
//registry.npmjs.org/:_authToken=abcde-abcde-abcde-abcde
```

My doubts would therefore be:
- Can all lines except those starting with `//` always be ignored for this purpose?
- Is there only ever one `//` registry line in an `.npmrc`?
- Do I need to generate the `npmrc.registry` field to pass to `registry-auth-token` or just the one for auth token?

**Comment by zkochan** [comment]
For reading the npmrc configs it is best to use the npm programmatic API. Believe me, the npm configs are very complex. You won't be able to cover all the use cases... 

You can look how I did it for pnpm [here](https://github.com/pnpm/pnpm/blob/master/src/bin/pnpm.ts#L100-L113)

**Comment by zkochan** [comment]
And you can pass the whole raw npm config object. registry-auth-token will look up all the keys it needs.

**Comment by rarkins** [comment]
I don't fully understand, so please let me try to fill the gaps.

If I understand correctly the way registry-auth-token works, it requires `npm` as a *library*, which lets npm do all the "hard work" of parsing `.npmrc` files from the file system?

If so, would it work if I wrote the `.npmrc` contents from memory to file in the current working directory before requiring registry-auth-token?

> And you can pass the whole raw npm config object.

What I have is an "ini" file format instead of object. So my confusion is what is the minimal steps I need to do to convert npmrc's "ini" format to object. e.g. split each line by `=`?

**Comment by zkochan** [comment]
ah, ok. You can either write it to the filesystem or you can parse it using [ini](https://www.npmjs.com/package/ini) and pass the parsed object to `registry-auth-token` via the npmrc option

**Comment by rarkins** [comment]
Thanks I will test this soon and report back if I can get it to work.

**Comment by felixfbecker** [comment]
For anyone who stumled across this, here is a perma link for the dead link to mater above: https://github.com/pnpm/pnpm/blob/eb3c671c586ad2ff34bcd776eb296470271c658f/src/bin/pnpm.ts#L100-L113
