### ISSUE TITLE
Fails to parse .npmrc files that use "_auth".

### ISSUE THREAD

**Issue by darkobits** [rexxars/registry-auth-token#22]
Given an `.npmrc` file with the following format:

```ini
registry=https://my.private.registry.com/foo/bar/npm/
_auth=myAuthToken
email=user@host.com
always-auth=true
```

_Note the trailing slash in the registry URL._

This library fails to return any auth info to its consumer, causing other tools that use it to fail to authenticate with the registry correctly.

The NPM client, however, is able to authenticate with `registry` without issue.

**Comment by rexxars** [comment]
Are you sure this is correct? I wrote a test for this and it seems to return the token correctly. In fact, it seems to me that the legacy token is _always_ returned, even if the URL does not match, which is actually a bug.

**Comment by darkobits** [comment]
Alright, upon further analysis, this appears to have been an issue in a transitive dependency using an older version of this package. Thanks for the follow-up, @rexxars, as it helped point me in the right direction.

Cheers!
