### ISSUE TITLE
Should we respect `always-auth`?

### ISSUE THREAD

**Issue by rexxars** [rexxars/registry-auth-token#23]
While researching #22, it seems to me like the legacy check is broken in that it does not respect the URL constraint that is given. When digging for the correct behaviour in the npm docs, I came across the `always-auth` flag.

The npm source code says:
> If a tarball is hosted on a different place than the manifest, only send credentials on `alwaysAuth`

The question then is what the correct behaviour is for this module. If `always-auth` is set to true, should we:
a) Only return token for matching URLs, regardless of `always-auth` flag (current behaviour)
b) Always return any configured token (first registry match, or global if registry token not set)?

I'd like your input on this, @zkochan and @leipert

**Comment by zkochan** [comment]
I think this package should ignore `always-auth`. How do you know what registry was used to resolve the tarball?

> b) Always return any configured token (first registry match, or global if registry token not set)?

this may accidentally send the tokens somewhere it should not be sent, compromising it.
