### ISSUE TITLE
Infinite loop on Windows 10

### ISSUE THREAD

**Issue by zkochan** [rexxars/registry-auth-token#3]
This line in the code https://github.com/rexxars/registry-auth-token/blob/master/index.js#L28 returns `c:\` on Windows, so the loop never ends.

**Comment by rexxars** [comment]
Thanks for reporting! That was... embarrassing :flushed: 
Fixed in `2.1.1`.

**Comment by zkochan** [comment]
:raised_hands: 

Thanks, I appreciate how fast you reacted!
